### ISSUE TITLE
Mismatch between the numbers of column of scores obtained from docking the compound with CANDOCK in the description of "Running the EGNN code" and the ones in "data.txt" in "input"

### ISSUE THREAD

**Issue by FrancisShizy** [chopralab/egnn#1]
The description of "Running the EGNN code" in"Usage" tells that"...The first column is the SMILES string for the molecule, the next 96 columns are the 96 scores obtained from docking the compound with CANDOCK.",  while the "data.txt" of "input" folder only has 2 columns of scores after the first column as SMILES string for each molecular. There is a mismatch between 96 columns in the description and only two columns in "data.txt".

**Comment by gwijewar** [comment]
We have selected the best two docking score functions by calculating Kappa for each docking score functions. Thanks for the comment.
